CREATE DATABASE IF NOT EXISTS conaf;
USE conaf;
CREATE TABLE survey (
    id  INT(20) NOT NULL,
    nombre VARCHAR(150) DEFAULT NULL,
    edad INT(3) NOT NULL,
    genero VARCHAR(15) NOT NULL,
    descgenero VARCHAR(100) DEFAULT NULL,
    discapacidad VARCHAR(2) DEFAULT NULL,
    descdiscapacidad VARCHAR(100) DEFAULT NULL,
    lenguaindigena VARCHAR(2) DEFAULT NULL,
    desclengua VARCHAR(100) DEFAULT NULL,
    q1 VARCHAR(2) NOT NULL,
    q2 VARCHAR(2) NOT NULL,
    q3 VARCHAR(2) NOT NULL, 
    q4 VARCHAR(2) NOT NULL,
    q5 VARCHAR(2) NOT NULL,
    q6 VARCHAR(2) NOT NULL,
    q7 VARCHAR(2) NOT NULL,
    q8 VARCHAR(2) NOT NULL,
    q9 VARCHAR(2) NOT NULL,
    q10 VARCHAR(2) NOT NULL,
    q11 VARCHAR(2) NOT NULL,
    q12 VARCHAR(2) NOT NULL,
    q13 VARCHAR(2) NOT NULL,
    q14 VARCHAR(2) NOT NULL,
    q15 VARCHAR(2) NOT NULL,
    PRIMARY KEY (id)
);